language: node_js
node_js:
  - '10'

cache: yarn

script:
  - yarn build-lib
  - ./node_modules/.bin/ng test natural --progress false --watch=false --browsers ChromeHeadlessCustom
  - ./node_modules/.bin/ng test demo --progress false --watch=false --browsers ChromeHeadlessCustom
  - yarn build-docs
  - yarn lint

jobs:
  include:
    - stage: publish docs
      node_js: '10'
      script:
        - yarn build-docs
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: dist/demo
        github-token: $GITHUB_TOKEN
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^master|develop$

    - stage: publish npm package
      node_js: '10'
      script:
        - yarn build-lib
      before_deploy:
        - rm .gitignore
        - cd dist/natural
      deploy:
        provider: npm
        skip-cleanup: true
        email: $NPM_API_EMAIL
        api_key: $NPM_API_KEY
        on:
          tags: true
